printWidth = 80
tabWidth = 2
useTabs = false
semi = false
singleQuote = false
trailingComma = "es5"
bracketSpacing = true
arrowParens = "always"
svelteIndentScriptAndStyle = false
plugins = ["prettier-plugin-svelte", "prettier-plugin-toml"]

[[overrides]]
files = "*.svelte"
options = { parser = "svelte" }
